CREATE TABLE LIBRARY(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  PATH VARCHAR UNIQUE
);

CREATE TABLE DIRECTORY(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  LIBRARY_ID INTEGER,
  PARENT_ID INTEGER,
  TITLE VARCHAR,
  COVER_ID INTEGER NULL,
  PATH VARCHAR,
  FOREIGN KEY(LIBRARY_ID) REFERENCES LIBRARY(ID),
  FOREIGN KEY(PARENT_ID) REFERENCES DIRECTORY(ID)
);

CREATE TABLE BOOK(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  LIBRARY_ID INTEGER,
  DIRECTORY_ID INTEGER,
  TITLE VARCHAR,
  FILENAME VARCHAR,
  EXT VARCHAR,
  PATH VARCHAR,
  FOREIGN KEY(DIRECTORY_ID) REFERENCES DIRECTORY(ID)
);

CREATE INDEX `IDX_BOOK_LIBRARY` ON `BOOK` (`LIBRARY_ID` ASC);
CREATE INDEX `IDX_BOOK_DIRECTORY` ON `BOOK` (`DIRECTORY_ID` ASC);
CREATE INDEX `IDX_BOOK_TITLE` ON `BOOK` (`TITLE`);
CREATE INDEX `IDX_BOOK_PATH` ON `BOOK` (`PATH`);
CREATE INDEX `IDX_DIRECTORY_LIBRARY` ON `DIRECTORY` (`LIBRARY_ID` ASC);
CREATE INDEX `IDX_DIRECTORY_TITLE` ON `DIRECTORY` (`TITLE`);
CREATE INDEX `IDX_DIRECTORY_PATH` ON `DIRECTORY` (`PATH`);
CREATE INDEX `IDX_DIRECTORY_PARENT` ON `DIRECTORY` (`PARENT_ID` ASC);
